version: "3"

# services:
# Uncomment the following block to enable gpu support
# bark:
#   deploy:
#     resources:
#       reservations:
#         devices:
#           - driver: nvidia
#             count: 1
#             capabilities: [gpu]
#     volumes:
#       - home:${HOME_FOLDER-/home/vscode}"
# Uncomment the following block to enable home folder persistence
# volumes:
#   home:
